### ISSUE TITLE
int android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by chejfj** [mmoamenn/LuckyWheel_Android#40]
After adding the list, the following error occurred when starting this project：
`java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at com.bluehomestudio.luckywheel.WheelView.drawImage(WheelView.java:133)
        at com.bluehomestudio.luckywheel.WheelView.onDraw(WheelView.java:245)
        at android.view.View.draw(View.java:21612)
        at android.view.View.updateDisplayListIfDirty(View.java:20481)
        at android.view.View.draw(View.java:21341)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at android.view.View.updateDisplayListIfDirty(View.java:20472)
        at android.view.View.draw(View.java:21341)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at android.view.View.updateDisplayListIfDirty(View.java:20472)
        at android.view.View.draw(View.java:21341)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at android.view.View.draw(View.java:21615)
        at android.view.View.updateDisplayListIfDirty(View.java:20481)
        at android.view.View.draw(View.java:21341)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at android.view.View.updateDisplayListIfDirty(View.java:20472)
        at android.view.View.draw(View.java:21341)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at android.view.View.updateDisplayListIfDirty(View.java:20472)
        at android.view.View.draw(View.java:21341)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at android.view.View.updateDisplayListIfDirty(View.java:20472)
        at android.view.View.draw(View.java:21341)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at android.view.View.updateDisplayListIfDirty(View.java:20472)
        at android.view.View.draw(View.java:21341)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at android.view.View.draw(View.java:21615)
        at com.android.internal.policy.DecorView.draw(DecorView.java:844)
        at android.view.View.updateDisplayListIfDirty(View.java:20481)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3735)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3530)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2867)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1820)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7782)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
        at android.view.Choreographer.doCallbacks(Choreographer.java:854)
        at android.view.Choreographer.doFrame(Choreographer.java:789)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

Android studio version:2021.2.1

**Comment by Shivamsharma21** [comment]
> Error Occurred After Starting the Project

FATAL EXCEPTION: main
                                                                                                    Process: com.example.myapplication, PID: 11019
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                                                    	at com.bluehomestudio.luckywheel.WheelView.drawImage(WheelView.java:133)
                                                                                                    	at com.bluehomestudio.luckywheel.WheelView.onDraw(WheelView.java:245)
                                                                                                    	at android.view.View.draw(View.java:23889)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22756)
                                                                                                    	at android.view.View.draw(View.java:23620)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22747)
                                                                                                    	at android.view.View.draw(View.java:23620)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22747)
                                                                                                    	at android.view.View.draw(View.java:23620)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22747)
                                                                                                    	at android.view.View.draw(View.java:23620)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22747)
                                                                                                    	at android.view.View.draw(View.java:23620)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22747)
                                                                                                    	at android.view.View.draw(View.java:23620)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22747)
                                                                                                    	at android.view.View.draw(View.java:23620)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22747)
                                                                                                    	at android.view.View.draw(View.java:23620)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
                                                                                                    	at android.view.View.draw(View.java:23892)
                                                                                                    	at com.android.internal.policy.DecorView.draw(DecorView.java:809)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22756)
                                                                                                    	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
                                                                                                    	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
                                                                                                    	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
                                                                                                    	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4939)
                                                                                                    	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4643)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3822)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:882)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)`//`
